# Numpy

In [1]:
import numpy as np

Numpy’s core contribution is a new data-type called an **array**.

An array is similar to a list, but numpy imposes some additional restrictions on how the data inside is organized.

NumPy arrays are somewhat like native Python lists, except that **Data must be homogeneous (all elements of the same type).**

These types must be one of the data types (dtypes) provided by NumPy:

* float64: 64 bit floating-point number
* int64: 64 bit integer
* bool: 8 bit True or False

In [4]:
x_1d = np.array([1,2,3]) # creat an array from a list

In [5]:
x_1d

array([1, 2, 3])

In [6]:
type(x_1d)

numpy.ndarray

In [7]:
x_1d[0] # the first element

1

### Indexing

m:n means [m,n)

In [10]:
print(x_1d[:2]) # from the beginning to position 2, which is always not included

[1 2]


In [11]:
print(x_1d[1:2]) # from position 1 to position 2 (not included)

[2]


In [12]:
print(x_1d[-1]) # the last element

3


In [13]:
print(x_1d[-3:-1]) # from the third-to-last element to the last element (not included)

[1 2]


In [14]:
print(x_1d[-3:]) # from the third-to-last element all the way to the end

[1 2 3]


### The shape matters

In [15]:
x_1d.shape

(3,)

In [16]:
y_1d = x_1d.reshape((3,1)) # This does not change x_1d

In [17]:
y_1d

array([[1],
       [2],
       [3]])

In [18]:
z_1d = x_1d.reshape((1,3))

In [19]:
z_1d

array([[1, 2, 3]])

In [20]:
x_1d

array([1, 2, 3])

In [21]:
x_1d.shape # x_1d itself has not been changed by the reshape command

(3,)

In [22]:
z_1d.shape

(1, 3)

### Operations

In [23]:
x_1d+z_1d

array([[2, 4, 6]])

In [24]:
x_1d-z_1d

array([[0, 0, 0]])

In [25]:
3*x_1d

array([3, 6, 9])

In [26]:
x_1d/3

array([0.33333333, 0.66666667, 1.        ])

In [31]:
y_1d

array([[1],
       [2],
       [3]])

In [32]:
y_1d.T #transpose

array([[1, 2, 3]])

In [33]:
y_1d

array([[1],
       [2],
       [3]])

In [34]:
z_1d

array([[1, 2, 3]])

In [35]:
z_1d @ y_1d # dot product

array([[14]])

In [36]:
x_1d

array([1, 2, 3])

In [37]:
x_1d.shape

(3,)

In [38]:
z_1d@x_1d

array([14])

In [39]:
y_1d@z_1d # matrix multiplication, not dot product

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

### Element-wise operations

Not math, just Python specific operations

In [40]:
z_1d * x_1d

array([[1, 4, 9]])

In [41]:
z_1d/x_1d

array([[1., 1., 1.]])

In [42]:
x_1d+3

array([4, 5, 6])

### Creating arrays

In [43]:
# create an array from a list. Can do this with one line - no need to name a 
# list first if you don't plan to use it later
mylist = [ 0.5, 0.25, 3]
x = np.array(mylist)

In [44]:
x

array([0.5 , 0.25, 3.  ])

In [45]:
a = np.zeros(5)

In [46]:
a

array([0., 0., 0., 0., 0.])

In [47]:
a = np.zeros(3,dtype=int)

In [48]:
a

array([0, 0, 0])

In [49]:
type(a[1])

numpy.int64

In [50]:
a.shape

(3,)

In [51]:
b = np.ones(5)

In [52]:
b

array([1., 1., 1., 1., 1.])

In [53]:
c = np.empty(6)

In [54]:
c # the array is not really empty. It contain garbage values to hold the places. 

array([0.0e+000, 1.5e-323, 0.0e+000, 0.0e+000, 0.0e+000, 0.0e+000])

## Exercise

Task: re-write the get_PV function using dot products

A dot product is
$$ 
(x_1 x_2 ... x_n) 
\begin{pmatrix}
y_1 \\
y_2 \\
... \\
y_n
\end{pmatrix}
= \sum_{i=1}^n x_i y_i
$$

In [57]:
def get_PV(FP,i,n):
    total = 0
    for j in range(n):
        total = total + FP/(1+i)**(j+1)
    return total

In [58]:
get_PV(126,0.10, 25)

1143.7070422968989

In [66]:
def get_PV2(FP,i,n):
    streams = FP*np.ones((1,n))
    # The following line uses comprehension. You can certainly do this with a regular for loop
    discount = np.array([(1/(1+i)**(t+1)) for t in range(n)]) 
    return streams@discount

In [67]:
get_PV2(126,0.1,25)

array([1143.7070423])

## Matrices

In [69]:
mylist = [[1,2,3],[4,5,6],[7,8,9]]

In [70]:
mylist

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [71]:
x_2d = np.array(mylist) # again, this is for illustration. Can do it with one line. No need to create a new list first.

In [72]:
x_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
x_2d.shape

(3, 3)

In [75]:
x_2d[1,1]

5

In [76]:
x_2d[1,:] # second row

array([4, 5, 6])

In [77]:
x_2d[:,2] # third column

array([3, 6, 9])

## Exercise

Find the 2nd and 3rd elements in the second row

In [79]:
x_2d[1,1:]

array([5, 6])

### The shape matters

In [80]:
x_2d.shape

(3, 3)

In [81]:
x_2d.reshape((1,9)) # Note again: this does not change x_2d. It just shows what happens if you reshape it. 

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [82]:
x_2d.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [84]:
x_2d = x_2d.reshape((9,1)) # This does change x_2d

In [85]:
x_2d

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [86]:
x_2d.shape = (3,3) # Another way to reshape and change x_2d

In [87]:
x_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [88]:
x_2d.shape

(3, 3)

In [89]:
rows, columns = x_2d.shape # This is a handy way to unpack the numbers of rows and columns of a matrix

In [90]:
rows

3

In [91]:
columns

3

## Matrix operations

In [2]:
z = np.empty((3,3))

In [3]:
z

array([[ 3.45126646e-31, -6.90253292e-31,  1.72563323e-31],
       [-6.90253292e-31,  1.50130091e-30, -4.65920972e-31],
       [ 1.72563323e-31, -4.65920972e-31,  2.67473151e-31]])

In [4]:
z[0,0]

3.451266460341962e-31

In [5]:
x = np.array([])

In [6]:
x

array([], dtype=float64)

In [7]:
x.shape

(0,)

In [8]:
z[:] = 3

In [9]:
z

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [10]:
z[:,1]

array([3., 3., 3.])

In [11]:
z = np.zeros((4,3))

In [12]:
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
A = np.array([[2,4,6],[3,4,7]])

In [17]:
A

array([[2, 4, 6],
       [3, 4, 7]])

In [18]:
A.T

array([[2, 3],
       [4, 4],
       [6, 7]])

In [19]:
A

array([[2, 4, 6],
       [3, 4, 7]])

In [20]:
B = np.array([3.5, 5, 19]).reshape((3,1))

In [21]:
B

array([[ 3.5],
       [ 5. ],
       [19. ]])

In [22]:
A@B

array([[141. ],
       [163.5]])

## Exercise

Create a matrix, and a vector. Try the product of them. 

In [23]:
A = np.array([[2,1],[1,1]])

In [24]:
B = np.array([[1,-1],[0,2]])

In [25]:
A

array([[2, 1],
       [1, 1]])

In [26]:
B

array([[ 1, -1],
       [ 0,  2]])

In [27]:
A@B

array([[2, 0],
       [1, 1]])

In [28]:
B@A

array([[1, 0],
       [2, 2]])

In [29]:
A*B # Don't do this!

array([[ 2, -1],
       [ 0,  2]])

In [30]:
A

array([[2, 1],
       [1, 1]])

In [31]:
A@np.eye(2)

array([[2., 1.],
       [1., 1.]])

In [32]:
np.eye(2)@B

array([[ 1., -1.],
       [ 0.,  2.]])

In [33]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [34]:
A

array([[2, 1],
       [1, 1]])

In [35]:
A2 = 1/A # not the inverse!

In [36]:
A2

array([[0.5, 1. ],
       [1. , 1. ]])

In [37]:
A@A2

array([[2. , 3. ],
       [1.5, 2. ]])

In [39]:
A_inverse = np.linalg.inv(A)

In [40]:
A_inverse

array([[ 1., -1.],
       [-1.,  2.]])

In [41]:
A@A_inverse

array([[1., 0.],
       [0., 1.]])

In [43]:
from numpy.linalg import inv

In [44]:
inv(A)

array([[ 1., -1.],
       [-1.,  2.]])

In [45]:
np.linalg.det(A)

1.0

In [46]:
np.linalg.det(B)

2.0

In [47]:
C = np.array([[1,2],[2,4]])

In [48]:
C

array([[1, 2],
       [2, 4]])

In [49]:
np.linalg.det(C)

0.0

## Exercise
Solve the following system of equations by hand. Then, solve it using linear algebra in Python.

$ 3x + 8y = 5 $ 

$ 4x + 11y = 7 $


Write the system as

$ A z = B $

The solution is

$ z = A^{-1} B $

In [51]:
A = np.array([[3,8],[4,11]])

In [52]:
B = np.array([[5],[7]])

In [53]:
B

array([[5],
       [7]])

In [54]:
inv(A)@B

array([[-1.],
       [ 1.]])

In [55]:
A

array([[ 3,  8],
       [ 4, 11]])

In [56]:
A-np.eye(2)*2

array([[1., 8.],
       [4., 9.]])

In [58]:
evals, evecs = np.linalg.eig(A)

In [59]:
evals

array([ 0.07179677, 13.92820323])

In [60]:
evecs

array([[-0.9390708 , -0.59069049],
       [ 0.34372377, -0.80689822]])