# Numpy

In [1]:
import numpy as np

Numpy’s core contribution is a new data-type called an **array**.

An array is similar to a list, but numpy imposes some additional restrictions on how the data inside is organized.

NumPy arrays are somewhat like native Python lists, except that **Data must be homogeneous (all elements of the same type).**

These types must be one of the data types (dtypes) provided by NumPy:

* float64: 64 bit floating-point number
* int64: 64 bit integer
* bool: 8 bit True or False

In [4]:
x_1d = np.array([1,2,3]) # creat an array from a list

In [5]:
x_1d

array([1, 2, 3])

In [6]:
type(x_1d)

numpy.ndarray

In [7]:
x_1d[0] # the first element

1

### Indexing

m:n means [m,n)

In [10]:
print(x_1d[:2]) # from the beginning to position 2, which is always not included

[1 2]


In [11]:
print(x_1d[1:2]) # from position 1 to position 2 (not included)

[2]


In [12]:
print(x_1d[-1]) # the last element

3


In [13]:
print(x_1d[-3:-1]) # from the third-to-last element to the last element (not included)

[1 2]


In [14]:
print(x_1d[-3:]) # from the third-to-last element all the way to the end

[1 2 3]


### The shape matters

In [15]:
x_1d.shape

(3,)

In [16]:
y_1d = x_1d.reshape((3,1)) # This does not change x_1d

In [17]:
y_1d

array([[1],
       [2],
       [3]])

In [18]:
z_1d = x_1d.reshape((1,3))

In [19]:
z_1d

array([[1, 2, 3]])

In [20]:
x_1d

array([1, 2, 3])

In [21]:
x_1d.shape # x_1d itself has not been changed by the reshape command

(3,)

In [22]:
z_1d.shape

(1, 3)

### Operations

In [23]:
x_1d+z_1d

array([[2, 4, 6]])

In [24]:
x_1d-z_1d

array([[0, 0, 0]])

In [25]:
3*x_1d

array([3, 6, 9])

In [26]:
x_1d/3

array([0.33333333, 0.66666667, 1.        ])

In [31]:
y_1d

array([[1],
       [2],
       [3]])

In [32]:
y_1d.T #transpose

array([[1, 2, 3]])

In [33]:
y_1d

array([[1],
       [2],
       [3]])

In [34]:
z_1d

array([[1, 2, 3]])

In [35]:
z_1d @ y_1d # dot product

array([[14]])

In [36]:
x_1d

array([1, 2, 3])

In [37]:
x_1d.shape

(3,)

In [38]:
z_1d@x_1d

array([14])

In [39]:
y_1d@z_1d # matrix multiplication, not dot product

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

### Element-wise operations

Not math, just Python specific operations

In [40]:
z_1d * x_1d

array([[1, 4, 9]])

In [41]:
z_1d/x_1d

array([[1., 1., 1.]])

In [42]:
x_1d+3

array([4, 5, 6])

### Creating arrays

In [43]:
# create an array from a list. Can do this with one line - no need to name a 
# list first if you don't plan to use it later
mylist = [ 0.5, 0.25, 3]
x = np.array(mylist)

In [44]:
x

array([0.5 , 0.25, 3.  ])

In [45]:
a = np.zeros(5)

In [46]:
a

array([0., 0., 0., 0., 0.])

In [47]:
a = np.zeros(3,dtype=int)

In [48]:
a

array([0, 0, 0])

In [49]:
type(a[1])

numpy.int64

In [50]:
a.shape

(3,)

In [51]:
b = np.ones(5)

In [52]:
b

array([1., 1., 1., 1., 1.])

In [53]:
c = np.empty(6)

In [54]:
c # the array is not really empty. It contain garbage values to hold the places. 

array([0.0e+000, 1.5e-323, 0.0e+000, 0.0e+000, 0.0e+000, 0.0e+000])

## Exercise

Task: re-write the get_PV function using dot products

A dot product is
$$ 
(x_1 x_2 ... x_n) 
\begin{pmatrix}
y_1 \\
y_2 \\
... \\
y_n
\end{pmatrix}
= \sum_{i=1}^n x_i y_i
$$

In [57]:
def get_PV(FP,i,n):
    total = 0
    for j in range(n):
        total = total + FP/(1+i)**(j+1)
    return total

In [58]:
get_PV(126,0.10, 25)

1143.7070422968989

In [66]:
def get_PV2(FP,i,n):
    streams = FP*np.ones((1,n))
    # The following line uses comprehension. You can certainly do this with a regular for loop
    discount = np.array([(1/(1+i)**(t+1)) for t in range(n)]) 
    return streams@discount

In [67]:
get_PV2(126,0.1,25)

array([1143.7070423])

## Matrices

In [69]:
mylist = [[1,2,3],[4,5,6],[7,8,9]]

In [70]:
mylist

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [71]:
x_2d = np.array(mylist) # again, this is for illustration. Can do it with one line. No need to create a new list first.

In [72]:
x_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
x_2d.shape

(3, 3)

In [75]:
x_2d[1,1]

5

In [76]:
x_2d[1,:] # second row

array([4, 5, 6])

In [77]:
x_2d[:,2] # third column

array([3, 6, 9])

## Exercise

Find the 2nd and 3rd elements in the second row

In [79]:
x_2d[1,1:]

array([5, 6])

### The shape matters

In [80]:
x_2d.shape

(3, 3)

In [81]:
x_2d.reshape((1,9)) # Note again: this does not change x_2d. It just shows what happens if you reshape it. 

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [82]:
x_2d.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [84]:
x_2d = x_2d.reshape((9,1)) # This does change x_2d

In [85]:
x_2d

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [86]:
x_2d.shape = (3,3) # Another way to reshape and change x_2d

In [87]:
x_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [88]:
x_2d.shape

(3, 3)

In [89]:
rows, columns = x_2d.shape # This is a handy way to unpack the numbers of rows and columns of a matrix

In [90]:
rows

3

In [91]:
columns

3

## Matrix operations

In [2]:
z = np.empty((3,3))

In [3]:
z

array([[ 3.45126646e-31, -6.90253292e-31,  1.72563323e-31],
       [-6.90253292e-31,  1.50130091e-30, -4.65920972e-31],
       [ 1.72563323e-31, -4.65920972e-31,  2.67473151e-31]])

In [4]:
z[0,0]

3.451266460341962e-31

In [5]:
x = np.array([])

In [6]:
x

array([], dtype=float64)

In [7]:
x.shape

(0,)

In [8]:
z[:] = 3

In [9]:
z

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [10]:
z[:,1]

array([3., 3., 3.])

In [11]:
z = np.zeros((4,3))

In [12]:
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
A = np.array([[2,4,6],[3,4,7]])

In [17]:
A

array([[2, 4, 6],
       [3, 4, 7]])

In [18]:
A.T

array([[2, 3],
       [4, 4],
       [6, 7]])

In [19]:
A

array([[2, 4, 6],
       [3, 4, 7]])

In [20]:
B = np.array([3.5, 5, 19]).reshape((3,1))

In [21]:
B

array([[ 3.5],
       [ 5. ],
       [19. ]])

In [22]:
A@B

array([[141. ],
       [163.5]])

## Exercise

Create a matrix, and a vector. Try the product of them. 

In [23]:
A = np.array([[2,1],[1,1]])

In [24]:
B = np.array([[1,-1],[0,2]])

In [25]:
A

array([[2, 1],
       [1, 1]])

In [26]:
B

array([[ 1, -1],
       [ 0,  2]])

In [27]:
A@B

array([[2, 0],
       [1, 1]])

In [28]:
B@A

array([[1, 0],
       [2, 2]])

In [29]:
A*B # Don't do this!

array([[ 2, -1],
       [ 0,  2]])

In [30]:
A

array([[2, 1],
       [1, 1]])

In [31]:
A@np.eye(2)

array([[2., 1.],
       [1., 1.]])

In [32]:
np.eye(2)@B

array([[ 1., -1.],
       [ 0.,  2.]])

In [33]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [34]:
A

array([[2, 1],
       [1, 1]])

In [35]:
A2 = 1/A # not the inverse!

In [36]:
A2

array([[0.5, 1. ],
       [1. , 1. ]])

In [37]:
A@A2

array([[2. , 3. ],
       [1.5, 2. ]])

In [39]:
A_inverse = np.linalg.inv(A)

In [40]:
A_inverse

array([[ 1., -1.],
       [-1.,  2.]])

In [41]:
A@A_inverse

array([[1., 0.],
       [0., 1.]])

In [43]:
from numpy.linalg import inv

In [44]:
inv(A)

array([[ 1., -1.],
       [-1.,  2.]])

In [45]:
np.linalg.det(A)

1.0

In [46]:
np.linalg.det(B)

2.0

In [47]:
C = np.array([[1,2],[2,4]])

In [48]:
C

array([[1, 2],
       [2, 4]])

In [49]:
np.linalg.det(C)

0.0

## Exercise
Solve the following system of equations by hand. Then, solve it using linear algebra in Python.

$ 3x + 8y = 5 $ 

$ 4x + 11y = 7 $


Write the system as

$ A z = B $

The solution is

$ z = A^{-1} B $

In [51]:
A = np.array([[3,8],[4,11]])

In [52]:
B = np.array([[5],[7]])

In [53]:
B

array([[5],
       [7]])

In [54]:
inv(A)@B

array([[-1.],
       [ 1.]])

## Eigenvalues

In [55]:
A

array([[ 3,  8],
       [ 4, 11]])

In [56]:
A-np.eye(2)*2

array([[1., 8.],
       [4., 9.]])

In [58]:
evals, evecs = np.linalg.eig(A)

In [59]:
evals

array([ 0.07179677, 13.92820323])

In [60]:
evecs

array([[-0.9390708 , -0.59069049],
       [ 0.34372377, -0.80689822]])

## Universal functions

In [2]:
w = np.array([[1,3],[3,5]])

In [3]:
np.log(w)

array([[0.        , 1.09861229],
       [1.09861229, 1.60943791]])

In [4]:
np.sin(w)

array([[ 0.84147098,  0.14112001],
       [ 0.14112001, -0.95892427]])

In [5]:
np.mean(w)

3.0

In [6]:
np.std(w)

1.4142135623730951

In [7]:
np.max(w)

5

In [8]:
np.min(w)

1

In [11]:
w = np.array([[1,3],[8,2]])

In [15]:
w

array([[1, 3],
       [8, 2]])

In [12]:
np.diff(w,axis=0)

array([[ 7, -1]])

In [14]:
np.diff(w,axis=1)

array([[ 2],
       [-6]])

In [16]:
w.sort(axis=0)

In [17]:
w

array([[1, 2],
       [8, 3]])

In [18]:
w.sort(axis=1)
w

array([[1, 2],
       [3, 8]])

## `linspace` and `arange`

In [19]:
# create an array from 2 to 13, of 5 elements
z = np.linspace(2,13,5)

In [20]:
z

array([ 2.  ,  4.75,  7.5 , 10.25, 13.  ])

In [21]:
z = np.linspace(1,15,30)
z

array([ 1.        ,  1.48275862,  1.96551724,  2.44827586,  2.93103448,
        3.4137931 ,  3.89655172,  4.37931034,  4.86206897,  5.34482759,
        5.82758621,  6.31034483,  6.79310345,  7.27586207,  7.75862069,
        8.24137931,  8.72413793,  9.20689655,  9.68965517, 10.17241379,
       10.65517241, 11.13793103, 11.62068966, 12.10344828, 12.5862069 ,
       13.06896552, 13.55172414, 14.03448276, 14.51724138, 15.        ])

In [22]:
np.arange(0,12,2)

array([ 0,  2,  4,  6,  8, 10])

In [23]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [24]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
type(range(10))

range

In [27]:
print(list(range(10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [29]:
range(10)[0]

0

## Mutability and array copying

In [30]:
w = 3
v = w
v = v+2

In [31]:
w

3

In [32]:
h = [1,2]
c = h
c[0] = 9
c

[9, 2]

In [33]:
h

[9, 2]

In [34]:
a = np.array([42,44])
b = a
b[0] = 2

In [35]:
b

array([ 2, 44])

In [36]:
a

array([ 2, 44])

In [37]:
c = np.copy(a)
c[:] =1
c

array([1, 1])

In [38]:
a

array([ 2, 44])

## Extraction

In [39]:
z = np.linspace(2,4,5)

In [40]:
z

array([2. , 2.5, 3. , 3.5, 4. ])

In [41]:
index = np.array((0,2,3))

In [42]:
index

array([0, 2, 3])

In [43]:
z[index]

array([2. , 3. , 3.5])

In [44]:
d = np.array([0,1,1,0,1], dtype=bool)

In [45]:
d

array([False,  True,  True, False,  True])

In [46]:
z[d]

array([2.5, 3. , 4. ])

## Vectorized functions

In [47]:
a = np.array([0.5,2.3,4.6])

In [48]:
c = 0.5

In [49]:
np.exp(-0.5*c**2)

0.8824969025845955

In [50]:
np.exp(-0.5*a**2)

array([8.82496903e-01, 7.10053537e-02, 2.54193465e-05])

In [51]:
# This does not always work. As an example,
def f(x):
    return 1 if x>0 else 0

In [52]:
f(c)

1

In [53]:
f(a) # this does not work

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [54]:
f = np.vectorize(f) # This makes the function work for an array

In [55]:
f(a)

array([1, 1, 1])

## Comparisons are done element by element

In [56]:
c < 0

False

In [57]:
c

0.5

In [58]:
a

array([0.5, 2.3, 4.6])

In [59]:
a > 1

array([False,  True,  True])

In [60]:
z = a[a>1]

In [61]:
z

array([2.3, 4.6])

In [62]:
z == a[0:2]

array([False, False])

In [63]:
z == a[1:]

array([ True,  True])

In [64]:
a[1:]

array([2.3, 4.6])