## Econ 481F Midterm Exam 1 answer key

## Part 1. Python questions

1. Predict and write down the output of the following Python code (2 points each, 20 points total)

In [1]:
mylist = ['eggs', 'ham', '16', True ]

In [2]:
mylist[1]

'ham'

In [3]:
mylist[-1]

True

In [4]:
mylist[1:3]

['ham', '16']

In [5]:
mylist[-4:-1]

['eggs', 'ham', '16']

In [6]:
mylist[-4:]

['eggs', 'ham', '16', True]

In [7]:
type(mylist[2])

str

In [8]:
mylist[1]=='eggs'

False

In [9]:
mylist[2] = 15
type(mylist[2])

int

In [10]:
mylist.append(7)
len(mylist)

5

In [11]:
x = ('USA',"Russia")
type(x)

tuple

    2. Write a block of code to print out the following output (assuming that the list has not been altered). Use a loop. (5 points)
    
`Element 1 of mylist is eggs`
    
`Element 2 of mylist is ham`
    
`Element 3 of mylist is 16`
    
`Element 4 of mylist is True`

In [14]:
mylist = ['eggs', 'ham', '16', True ]
for i, item in enumerate(mylist):
    print(f'Element {i+1} of mylist is {mylist[i]}')

Element 1 of mylist is eggs
Element 2 of mylist is ham
Element 3 of mylist is 16
Element 4 of mylist is True


    3. Unpack the first two elements of "mylist" into two variables, called "food1" and "food2" with one line of code. (5 points)

In [15]:
food1, food2 = mylist[:2]

In [16]:
print(food1, food2) # to confirm, not required

eggs ham


    4. Use a loop to create a new list named "mylist2". Each element of "mylist2" should contain the length of the corresponding element in "mylist1". (5 points)

In [25]:
# The question did not say what mylist1 is. The following line is not required. 
# However, please note that mylist1 needs to contain elements that have their own length,
# such as a string. 
mylist1 = ['teacher','dog','cats']

In [26]:
mylist2 = []
for i, item in enumerate(mylist1):
    mylist2.append(len(item))

In [27]:
mylist2

[7, 3, 4]

    5. Use zip and a loop to print out:
    
`The length of XXX is YYY` 
    
    for each element in "mylist1". Note that "XXX" is the element of mylist1, and "YYY" is the corresponding element in mylist2. (5 points)

In [28]:
for item, length in zip(mylist1, mylist2):
    print(f'The length of {item} is {length}')

The length of teacher is 7
The length of dog is 3
The length of cats is 4


    6. Predict the output of the following code (5 points)
```
for x in range(6):
    if x**3 == 64:
        continue
    else:
        print(x**3)
```

In [29]:
for x in range(6):
    if x**3 == 64:
        continue
    else:
        print(x**3)

0
1
8
27
125


    7. The following code is problematic. Fix it. (5 points)

```
    newlist = list(range(10))
    i = 0
    while i<10:
       print(newlist[i])
```

In [30]:
newlist = list(range(10))
i = 0
while i<10:
    print(newlist[i])
    i += 1 # without this line, the loop will run indefinitely because i will always be 0

0
1
2
3
4
5
6
7
8
9


    8. Write a function to complete the following: if the input is a float or an integer, calculate its square root; if the input is a string, print "this is a string"; if the input is a list, print the list. (8 points)

Hint: if `x` is a float, then `type(x) is float` returns `True`.

In [31]:
import numpy as np

In [36]:
def f(x):
    if type(x) is int or type(x) is float:
        return np.sqrt(x)
    elif type(x) is str:
        print('this is a string')
    elif type(x) is list:
        print(x)

In [37]:
print(f(4))

2.0


In [38]:
f('hello')

this is a string


In [39]:
f(mylist)

['eggs', 'ham', '16', True]


    9. Predict the result of the following code (8 points).

```
v1 = np.array([4, 2, 9])
v2 = np.array([2, 5, 1])
```

In [41]:
v1 = np.array([4, 2, 9])
v2 = np.array([2, 5, 1])

In [42]:
v1 * v2

array([ 8, 10,  9])

In [43]:
v1 @ v2

27

    10. Consider these two matrices: 
$ A = 
\begin{bmatrix}
1 & 7 \\
2 & 4
\end{bmatrix},
B= 
\begin{bmatrix}
3 & 3 \\
5 & 2
\end{bmatrix}.
$

a. Calculate $A \times B$ by hand. Show all your work (8 points)
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

In [44]:
# Verify with Python:
A = np.array([[1,7],[2,4]])
B = np.array([[3,3],[5,2]])

In [45]:
A @ B

array([[38, 17],
       [26, 14]])

b. Write code to solve the following equations.(5 points)
$$
x + 7 y = 3 \\
2x + 4 y = 5
$$

In [47]:
np.linalg.inv(A) @ B[:,0]

array([2.3, 0.1])

## Part 2. Economics with Python

1. Suppose you purchase a coupon bond with 20 years to maturity for \\$950. It pays coupons of \\$70 a year. The face value is \$1000. 

a. Write down the formula that you would use to calculate the yield to maturity of this bond: (4 points)
$$
950 = \sum_{t=1}^{20} \frac{70}{(1+i)^t} + \frac{1000}{(1+i)^{20}}
$$

b. Show how you would use Python to compute the yield to maturity. Show all your code, including defining funtions and importing packages, etc. (5 points)  
your code:

In [58]:
from scipy.optimize import newton

In [76]:
def get_PV2(FP,i,n):
    discount = np.array([(1 / (1+i))**(t+1) for t in range(n)])
    stream = np.ones((1,n))*FP
    return stream @ discount.reshape(n,1)

In [77]:
def g(i):
    return get_PV2(FP,i,n)+1000/(1+i)**20 - 950

In [78]:
FP = 70
n = 20
newton(g,0.1)

array([[0.07490091]])

c. Suppose after 1 year, you must sell the bond to pay for tuition. Further suppose that the interest rate has risen and the price of the bond has fallen to $850. What is the size of the capital gain or loss? What is your rate of return for holding the bond for 1 year? show all your calculations. (5 points)

* The capital loss is $950-850=100$
* The rate of return is:

$$
\frac{70+850-950}{950} = -3.2\%
$$



In [80]:
(70+850-950)/950

-0.031578947368421054

2.In recent months, market predictions for future inflation has risen. Use the demand and supply model for bonds, predict what happens to bond prices and interest rates. Make sure to draw a diagram to support your answer (8 points)

Higher inflation lowers buyers’ expected real interest rate, and reduces bond demand. It also lowers the real cost of borrowing for the issuer, and therefore increases bond supply. The prediction is that bond prices will decrease, and the interest rate rises. 

Here is a [diagram](https://drive.google.com/file/d/1IYeJjR0iDSPZAaRhiwmEbNe1KRKmPsnU/view?usp=sharing)